name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploys whenever code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify Node version, adjust as needed

    - name: Install dependencies
      run: npm install

    - name: Build the project
      # Pass the environment variable securely from GitHub Secrets
      env:
        VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist